### ISSUE TITLE
Failed to build on PostgreSQL 9.6

### ISSUE THREAD

**Issue by ad-m** [tvondra/shared_ispell#2]
```
03:18 $ sudo make install
 $ LANGUAGE="en_US" sudo make install
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -g -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -I/usr/include/mit-krb5 -fPIC -pie -fno-omit-frame-pointer -fpic -fpic -I. -I./ -I/usr/include/postgresql/9.6/server -I/usr/include/postgresql/internal -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include/tcl8.6  -c -o src/shared_ispell.o src/shared_ispell.c
src/shared_ispell.c: In function ‘_PG_init’:
src/shared_ispell.c:191:5: warning: implicit declaration of function ‘RequestAddinLWLocks’ [-Wimplicit-function-declaration]
     RequestAddinLWLocks(1);
     ^
src/shared_ispell.c: In function ‘ispell_shmem_startup’:
src/shared_ispell.c:245:31: warning: implicit declaration of function ‘LWLockAssign’ [-Wimplicit-function-declaration]
         segment_info->lock  = LWLockAssign();
                               ^
src/shared_ispell.c:245:29: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
         segment_info->lock  = LWLockAssign();
                             ^
src/shared_ispell.c: In function ‘copyIspellDict’:
src/shared_ispell.c:956:31: error: ‘IspellDict {aka struct <anonymous>}’ has no member named ‘flagval’
     memcpy(copy->flagval, dict->flagval, 255);
                               ^
<builtin>: recipe for target 'src/shared_ispell.o' failed
make: *** [src/shared_ispell.o] Error 1
```

```
=> select version();
                                                     version                                                     
-----------------------------------------------------------------------------------------------------------------
 PostgreSQL 9.6.3 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609, 64-bit
(1 wiersz)
```
